---
- name: System configuration on RHEL 9
  hosts: all
  become: yes

  tasks:
    - name: Set swappiness to 1
      sysctl:
        name: vm.swappiness
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Disable Transparent Huge Pages (THP)
      shell: |
        echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
        echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
      args:
        creates: /sys/kernel/mm/transparent_hugepage/enabled

    - name: Ensure THP is disabled on reboot
      lineinfile:
        path: /etc/rc.d/rc.local
        state: present
        line: |
          if test -f /sys/kernel/mm/transparent_hugepage/enabled; then echo never > /sys/kernel/mm/transparent_hugepage/enabled; fi
          if test -f /sys/kernel/mm/transparent_hugepage/defrag; then echo never > /sys/kernel/mm/transparent_hugepage/defrag; fi
      notify: make rc.local executable

    - name: Enable and start chronyd
      systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disable IPv6
      sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

  handlers:
    - name: make rc.local executable
      file:
        path: /etc/rc.d/rc.local
        mode: '0755'
